name: SMPTradingHouse
version: ${project.version}
main: org.tfsmp.smptradinghouse.SMPTradingHouse
api-version: 1.13
authors: [super]
description: The workings of TotalFreedom SMP's Trading House.
commands:
  opentradinghouse:
    aliases: [oth]
  tradinghousetest:
    aliases: [tht]